### ISSUE TITLE
Images aren't being cropped correctly

### ISSUE THREAD

**Issue by Samwalton9** [catleeball/tmnt_wikipedia_bot#18]
Earlier today it looks like the bot started cropping incorrectly, leaving the text bar visible in images. See https://twitter.com/wiki_tmnt/status/1267683099447525376, for example.

**Comment by catleeball** [comment]
Ah yeah, it looks like the website added a header and bumped everything down a few pixels. This is my bad for doing the hacky bit of "open a chrome subprocess and take a screenshot of glench.com/tmnt". I'll fix it with something maybe a smidge prettier. ✨

**Comment by catleeball** [comment]
This particular issue was solved by calling [WebScreenshot](https://github.com/catleeball/WebScreenShot). I need to roll back to the old cropping / padding logic though for nicer thumbnails

Thanks for the heads up on this issue!
