### ISSUE TITLE
Comma handling

### ISSUE THREAD

**Issue by metasj** [catleeball/tmnt_wikipedia_bot#6]
Four-word titles ending in a two-word phrase after a comma, the last two words should sometimes both be in the subtitle.  Hard to say exactly when.

**Comment by catleeball** [comment]
Thanks for the idea! I might close this one as out of scope though. It's a bit of a corner case, and could cause a bit of trouble modeling it correctly. For now, I'll leave word spacing >3 words to Glench's logo generator.
